name: Create pr on branch creation

# Controls when the workflow will run
on:
  create:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Creating PR based on branch name ${{ github.ref_name }}
        run: echo Hello, world!
