name: Create pr on branch creation

# Controls when the workflow will run
on:
  create:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  create-pr-for-new-branch:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      # Runs a single command using the runners shell
      - name: Creating PR based on branch name ${{ github.ref_name }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/KarmaComputing/create-pull-request-on-branch-creation/pulls \
          -d '{"title":"Amazing new feature","body":"Please pull these awesome changes in!","head":"${{ github.ref_name }}","base":"master","draft":"true"}'
